name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.3.0
        with:
          # You can target a repository in a different organization
          # to the issue
          project-url: https://github.com/orgs/QPong/projects/1
          github-token: ${{ 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 }}
          labeled: bug, needs-triage
          label-operator: OR
