name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run styles check
      run: tox -elint
  json-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Validate ecosystem.json
      run: tox -ejson
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]
    env:
      DISPLAY: ":0"  # X
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up tox env
      run: |
        pver=${{ matrix.python-version }}
        tox_env="-epy${pver/./}"
        echo tox_env
        echo TOX_ENV=$tox_env >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install xvfb and pulseaudio
      run: |
          sudo apt-get install xvfb pulseaudio
    - name: Test using tox envs under xvfb
      run: |
        pulseaudio -D --start
        xvfb-run --auto-servernum python -m unittest -v
  coverage:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":0"
      SDL_VIDEODRIVER: "dummy"
      SDL_AUDIODRIVER: "disk"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Install xvfb and pulseaudio
      run: |
          sudo apt-get install xvfb pulseaudio
    - name: Run coverage under xvfb
      run: |
        pulseaudio -D --start
        xvfb-run --auto-servernum coverage3 run -m pytest
        coverage3 report --fail-under=80
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
          python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Run black
      run: tox -eblack
